events {}

http {
    log_format ngxray '$remote_addr - [$time_local] "$request" $status '
                      'ct=$upstream_connect_time rt=$upstream_response_time pid=$pid';

    access_log /logs/access.log ngxray;
    error_log  /logs/error.log warn;

    upstream backend {
        server 127.0.0.1:8080;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}
